import { Router } from 'express';

import authRoutes from './auth.routes';
import employeeRoutes from './employee.routes';
import shiftRoutes from './shift.routes';
import departmentRoutes from './department.routes';
import overtimeRoutes from './overtime.routes';
import regularizationRoutes from './regularization.routes';
import attendanceRoutes from './attendance.routes';
import leaveRoutes from './leave.routes';
import performanceRoutes from './performance.routes';
import kpiRoutes from './kpi.routes';
import reimbursementRoutes from './reimbursement.routes';
import payrollRoutes from './payroll.routes';
import payslipsRoutes from './payslips.routes';
import loansRoutes from './loans.routes';
import notificationRoutes from './notification.routes';
import companyRoutes from './company.routes';
import userRoutes from './user.routes';
import roleRoutes from './role.routes';
import accessControlRoutes from './access-control.routes';
import supportRoutes from './support.routes';
import onboardingRoutes from './onboarding.routes';
import publicRoutes from './public.routes';
import newjoiningRoutes from './newjoining.routes';
import recruitmentRoutes from './recruitment.routes';
import assetsRoutes from './assets.routes';
import offboardingRoutes from './offboarding.routes';
import reportsRoutes from './reports.routes';
import mobileRoutes from './mobile.routes';
import biometricRoutes from './biometric.routes';

const router = Router();

router.use('/auth', authRoutes);
router.use('/employees', employeeRoutes);
router.use('/shifts', shiftRoutes);
router.use('/departments', departmentRoutes);
router.use('/overtime', overtimeRoutes);
router.use('/regularization', regularizationRoutes);
router.use('/attendance', attendanceRoutes);
router.use('/leaves', leaveRoutes);
router.use('/performance', performanceRoutes);
router.use('/kpis', kpiRoutes);
router.use('/reimbursements', reimbursementRoutes);
router.use('/payroll', payrollRoutes);
router.use('/payslips', payslipsRoutes);
router.use('/loans', loansRoutes);
router.use('/notifications', notificationRoutes);
router.use('/companies', companyRoutes);
router.use('/users', userRoutes);
router.use('/roles', roleRoutes);
router.use('/access-control', accessControlRoutes);
router.use('/support', supportRoutes);
router.use('/onboarding', onboardingRoutes);
router.use('/public', publicRoutes);
router.use('/newjoining', newjoiningRoutes);
router.use('/recruitment', recruitmentRoutes);
router.use('/assets', assetsRoutes);
router.use('/offboarding', offboardingRoutes);
router.use('/reports', reportsRoutes);
router.use('/mobile', mobileRoutes);
router.use('/biometric', biometricRoutes);

export default router;